[package]
name = "upb-rs-wire"
version = "0.1.2"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Wire-format reader/encoder for upb-rs, mirroring upb/wire/reader.c and upb_EpsCopyInputStream"

[dependencies]
upb-rs-core = { version = "0.1.0", path = "../upb-rs-core" }
upb-rs-mini-table = { version = "0.1.0", path = "../upb-rs-mini-table" }
serde = { workspace = true }
serde_json = { workspace = true }
